### ISSUE TITLE
Error connecting to some Electrum servers

### ISSUE THREAD

**Issue by jp1ac4** [wizardsardine/liana#1275]
Possibly related to https://github.com/bitcoindevkit/rust-electrum-client/issues/144.

Some Electrum servers are not working with Liana:

![image](https://github.com/user-attachments/assets/514ce863-add1-4f32-9650-7598c18de90f)

```
  2024-09-05T16:56:33.917061Z  INFO electrum_client::client:182: Succesfully created new client

  2024-09-05T16:56:34.039764Z  WARN electrum_client::client:182: call 'internal_raw_call_with_vec' failed after 2 attempts

  2024-09-05T16:56:35.878115Z  INFO electrum_client::raw_client:205: Trying to connect to 35.225.54.191:50002 (attempt 1/1) with timeout 3s

  2024-09-05T16:56:36.116295Z  WARN electrum_client::client:182: call 'internal_raw_call_with_vec' failed with EOF while parsing a value at line 1 column 0, retry: 1/1

  2024-09-05T16:56:38.118850Z  INFO electrum_client::raw_client:205: Trying to connect to 35.225.54.191:50002 (attempt 1/1) with timeout 3s

  2024-09-05T16:56:38.234847Z  INFO electrum_client::client:182: Succesfully created new client

  2024-09-05T16:56:38.354514Z  WARN electrum_client::client:182: call 'internal_raw_call_with_vec' failed after 2 attempts
```

h/t @darosior

**Comment by jp1ac4** [comment]
Running lianad with "ssl://electrum.blockstream.info:50002" is working for me sometimes.

**Comment by darosior** [comment]
It also happens in the settings, where it used to freeze the GUI completely for 180s (fixed in #1277).

**Comment by pythcoiner** [comment]
tested acinq & setup a ssl electrum at ssl://pythcoiner.dev:50002
![image](https://github.com/user-attachments/assets/ae0784e1-bffe-45ae-8867-c8f381ae8cd3)
![image](https://github.com/user-attachments/assets/7e5f7f63-24da-41d9-92b7-aad3b46e144e)

every thing looks fine in my nginx logs

**Comment by pythcoiner** [comment]
we still cannot connect to server using self-signed certificates but i open #1300 for this specific issue

**Comment by darosior** [comment]
As we uncovered where the issue was coming from, i'm dropping the v7 milestone for this issue. Not supporting self-signed certs (#1300) and having to manually add the `ssl://` prefix (#1291) is not ideal but needs not be a blocker for the release.

**Comment by nondiremanuel** [comment]
Should we merge this and #1300 to not have to keep track of two issues? Do you see any downside in doing that?

**Comment by pythcoiner** [comment]
i think #1300 address the remaining issue

**Comment by nondiremanuel** [comment]
I would close this then if you are ok
